homeassistant: false
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mosquitto
serial:
  port: /dev/ttyUSB0
frontend:
  port: 8080
devices:
  '0x54ef44100064b0cb':
    friendly_name: 'test_device_1'
  '0x54ef441000811c36':
    friendly_name: 'test_device_2'
