services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto-iot
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped
    environment:
      - TZ=Asia/Singapore
    networks:
      - mqtt-network

  paho_mqtt:
    build: ./paho_mqtt
    image: cpf-iot/hardware
    container_name: cpf_iot_runner
    depends_on:
      - mosquitto
      - hardware_service
    networks:
      - mqtt-network
    environment:
      - TZ=Asia/Singapore
    restart: unless-stopped

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    container_name: zigbee2mqtt-iot
    ports:
      - "8080:8080"
    volumes:
      - ./zigbee2mqtt/data:/app/data
      - ./zigbee2mqtt/log:/app/data/log
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      - TZ=Asia/Singapore
    restart: unless-stopped
    depends_on:
      - mosquitto
    networks:
      - mqtt-network

  hardware_service:
    build: ./hardware_service
    image: cpf-iot/hardware-service
    container_name: hardware_service
    network_mode: host
    restart: unless-stopped
    environment:
      - TZ=Asia/Singapore

networks:
  mqtt-network:
    driver: bridge
