services:
  hardware_service:
    image: xiaoyeqiu514/cpf-iot-hardware
    container_name: hardware_service
    volumes:
      - ./hardware_service:/app/data
    network_mode: host
    restart: unless-stopped
    environment:
      - TZ=Asia/Singapore

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto-iot
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped
    depends_on:
      - hardware_service
    environment:
      - TZ=Asia/Singapore
    networks:
      - mqtt-network

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    container_name: zigbee2mqtt-iot
    ports:
      - "8080:8080"
    volumes:
      - ./zigbee2mqtt/data:/app/data
      - ./zigbee2mqtt/log:/app/data/log
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      - TZ=Asia/Singapore
    restart: unless-stopped
    depends_on:
      - mosquitto
      - hardware_service
    networks:
      - mqtt-network

  message_router:
    image: xiaoyeqiu514/cpf-iot-message-router
    container_name: message_router
    depends_on:
      - mosquitto
      - zigbee2mqtt
      - hardware_service
    networks:
      - mqtt-network
    environment:
      - TZ=Asia/Singapore
      - CONNECTION_STRING=${CONNECTION_STRING}
    restart: unless-stopped

networks:
  mqtt-network:
    driver: bridge
