services:
  hardware_service:
    image: xiaoyeqiu514/cpf-iot-hardware
    container_name: hardware_service
    volumes:
      - ./hardware_service:/app/data
    network_mode: host
    restart: unless-stopped
    environment:
      - TZ=Asia/Singapore

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto-iot
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/certs:/mosquitto/certs
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped
    depends_on:
      - hardware_service
    environment:
      - TZ=Asia/Singapore
    network_mode: host

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    container_name: zigbee2mqtt-iot
    volumes:
      - ./zigbee2mqtt/data:/app/data
      - ./mosquitto/certs:/app/certs
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      - TZ=Asia/Singapore
    restart: unless-stopped
    depends_on:
      - mosquitto
      - hardware_service
      - nginx
    network_mode: host

  message_router:
    image: xiaoyeqiu514/cpf-iot-message-router:latest
    container_name: message_router
    volumes:
      - ./message_router/data:/app/data
      - ./mosquitto/certs:/app/certs
    depends_on:
      - mosquitto
      - zigbee2mqtt
      - hardware_service
    network_mode: host
    environment:
      - TZ=Asia/Singapore
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx-reverse-proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    network_mode: host
    restart: unless-stopped
